version: '3'

services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile.${ENVIRONMENT}
    depends_on:
      - mongodb

  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"


