version: '3'

services:
  app:
    environment:
      - DATABASE=mongodb://sendgrid-eventkit-lambda-mongodb-mongo:27017/sendgrid
      - ENVIRONMENT=travis
      - TESTFILE=./testdata/events.json
