version: '3'

services:
  app:
    volumes:
      - .:/var/task
    environment:
      - DATABASE=mongodb://sendgrid-eventkit-lambda-mongodb-mongo:27017/sendgrid
      - ENVIRONMENT=${ENVIRONMENT}
      - TESTFILE=${TESTFILE}
      - LEGACY_WEBHOOK_URI=https://lambda-test.requestcatcher.com/test